application: memoryapp
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: cards.py
  login: required